# Generated by Django 6.0b1 on 2025-11-16 19:41

import django.db.models.deletion
import djangx.utils.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], help_text='The academic term name', max_length=6, unique=True)),
                ('order', models.PositiveIntegerField(default=0, editable=False, help_text='Display order (automatically assigned based on position in choices)')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(djangx.utils.models.mixins.OrderedChoiceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BEGINNER', 'Beginner'), ('PP1', 'Pre-Primary 1'), ('PP2', 'Pre-Primary 2'), ('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8'), ('GRADE_9', 'Grade 9'), ('GRADE_10', 'Grade 10'), ('GRADE_11', 'Grade 11'), ('GRADE_12', 'Grade 12')], help_text='The school level name', max_length=8, unique=True)),
                ('alt_name', models.CharField(blank=True, help_text='Alternative name for the school level (optional)', max_length=50, verbose_name='Alternative Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of this school level')),
                ('category', models.CharField(choices=[('PRE_SCHOOL', 'Pre-School'), ('PRE_PRIMARY', 'Pre-Primary'), ('PRIMARY', 'Primary'), ('JUNIOR_SECONDARY_SCHOOL', 'Junior Secondary School'), ('SENIOR_SECONDARY_SCHOOL', 'Senior Secondary School')], editable=False, help_text='Education category (automatically assigned)', max_length=23)),
                ('order', models.PositiveIntegerField(default=0, editable=False, help_text='Display order (automatically assigned based on position in choices)')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('name', 'category')},
            },
            bases=(djangx.utils.models.mixins.OrderedChoiceMixin, djangx.utils.models.mixins.CategoryAssignmentMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Learner's first name", max_length=30)),
                ('last_name', models.CharField(help_text="Learner's last name", max_length=30)),
                ('other_names', models.CharField(blank=True, help_text="Learner's other names (optional)", max_length=50)),
                ('date_of_birth', models.DateField(blank=True, help_text="Learner's date of birth (optional)", null=True)),
                ('enrollment_date', models.DateField(auto_now_add=True, help_text='Date when the learner was enrolled')),
                ('school_level', models.ForeignKey(help_text='The school level this learner is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='app.schoollevel')),
            ],
        ),
        migrations.CreateModel(
            name='TermFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fee amount in KES', max_digits=10)),
                ('school_level', models.ForeignKey(help_text='The school level this fee applies to', on_delete=django.db.models.deletion.CASCADE, related_name='term_fees', to='app.schoollevel')),
                ('term', models.ForeignKey(help_text='Academic term', on_delete=django.db.models.deletion.CASCADE, to='app.schoolterm')),
            ],
            options={
                'ordering': ['school_level__order', 'term__order'],
                'unique_together': {('school_level', 'term')},
            },
        ),
    ]
